name: chunkah
on:
  workflow_dispatch: # allow manually triggering builds

permissions: {}

concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  chunkah:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compressed: ["", "--compressed"]
    steps:
      - name: Free disk space
        uses: hastd/free-disk-space@v0.1.2
        with:
          skip-if-available: 64G

      - name: Run Chunkah
        env:
          COMPRESSED: ${{ matrix.compressed }}
        run: |
          set -euxo pipefail
          image_ref='ghcr.io/secureblue/kinoite-main-hardened:latest'
          podman pull "${image_ref}"
          temp_dir="$(mktemp -d)"
          config_file="${temp_dir}/chunkah-config.json"
          podman inspect "${image_ref}" > "${config_file}"
          oci_dir="${temp_dir}/oci-out"
          podman run --rm -v "${temp_dir}:${temp_dir}" \
            --mount="type=image,src=${image_ref},destination=/chunkah" \
            quay.io/coreos/chunkah:dev build --config "${config_file}" \
            ${COMPRESSED} --prune /sysroot/ --max-layers 128 \
            --label ostree.commit- --label ostree.final-diffid- \
            -t localhost/secureblue-chunkah-test:latest --output "oci:${oci_dir}"
          podman unshare skopeo copy "oci:${oci_dir}" containers-storage:localhost/secureblue-chunkah-test:latest

      - name: Print manifest (local)
        run: |
          podman unshare skopeo inspect -n containers-storage:localhost/secureblue-chunkah-test:latest
