name: chunkah
on:
  workflow_dispatch:

permissions: {}

concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  chunkah:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        tag:
          - latest
    steps:
      - name: Free disk space
        uses: hastd/free-disk-space@v0.1.2
        with:
          skip-if-available: 64G

      - name: Build Chunkah image
        run: |
          git clone https://github.com/coreos/chunkah.git
          cd chunkah
          storage_dir=$(podman info -f '{{.Store.GraphRoot}}')
          podman run -v "$PWD:$PWD" -w "$PWD" -v "${storage_dir}:${storage_dir}" quay.io/podman/stable sh -eu <<EOF
          dnf install -y just rustup
          rustup-init -y
          rustup toolchain install stable
          printf '[storage]\ngraphroot = "%s"\n' "${storage_dir}" > /etc/containers/storage.conf
          just buildimg
          EOF

      - name: Run Chunkah
        env:
          IMAGE_TAG: ${{ matrix.tag }}
        run: |
          set -euxo pipefail
          image_ref="ghcr.io/secureblue/kinoite-main-hardened:${IMAGE_TAG}"
          podman pull "${image_ref}"
          temp_dir="$(mktemp -d)"
          config_file="${temp_dir}/chunkah-config.json"
          podman inspect "${image_ref}" > "${config_file}"
          oci_dir="${temp_dir}/oci-out"
          podman run --rm -v "${temp_dir}:${temp_dir}" \
            --mount="type=image,src=${image_ref},destination=/chunkah" \
            localhost/chunkah build --config "${config_file}" \
            --compressed --prune /sysroot/ --max-layers 128 \
            --label ostree.commit- --label ostree.final-diffid- \
            -t "localhost/secureblue-kinoite-chunkah:${IMAGE_TAG}" --output "oci:${oci_dir}"

          manifest_digest=$(jq -cr '.manifests[0].digest' "${oci_dir}/index.json")
          cp "${oci_dir}/blobs/sha256/${manifest_digest#sha256:}" "manifest-${IMAGE_TAG}.json"

      - name: Upload manifest
        uses: actions/upload-artifact@v7
        with:
          path: ./manifest-${{ matrix.tag }}.json
          if-no-files-found: error
          archive: false

      - name: Pretty-print manifest
        run: |
          jq . manifest-*.json
