name: test
on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: Test slsa-verifier container install
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Install slsa-verifier
        uses: slsa-framework/slsa-verifier/actions/installer@ea584f4502babc6f60d9bc799dbbb13c1caa9ee6 # v2.7.1

      - name: Print version
        run: slsa-verifier version
