name: test
on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: Test gpg key
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Get GPG key
        run: |
          secureblue_gpg_fingerprint='26B4463ED8F313BC7E3FBDF9D9223AF0F47B3E41'
          curl -fLsS --retry 3 -O https://repo.secureblue.dev/secureblue.gpg
          gpg --show-keys --with-colons secureblue.gpg \
            | awk -F: '$1 == "fpr" || $1 == "fpr2" { print $10 }'
          gpg --show-keys --with-colons secureblue.gpg \
            | awk -F: '$1 == "fpr" || $1 == "fpr2" { print $10 }' \
            | grep -Fqx "${secureblue_gpg_fingerprint}"
          rpmkeys --import secureblue.gpg
